name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPORT: "true"
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/portfolio_db?schema=public"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build
